print("This is a mad lib game. kindly input the equired details of your choice")
name=input("Name:")
animal=input("Animal:")
adjective=input("Adjective:")
adverb=input("adverb:")
thing=input("thing:")
place=input("any room of the house:")
food=input("Food:")
furniture=input("Furniture:")
emotion=input("Emotion:")
print(name," went on a walk with their pet a ",animal,"on their way they saw a",adjective,"house they decided to explore it, inside they found a ", adverb, thing ," greeting them in the", place ,".", thing," was eating a ",food," sitting on a", furniture, "its expression was",emotion,".",name,"and his pet", animal, "made a quick escape after seeing that lol")